### ISSUE TITLE
pack express app failed

### ISSUE THREAD

**Issue by mylady** [jaredallard/nexe#157]
hi,
pack express app use nexe failed

Command: 
nexe -i ./bin/www -o test -r 4.2.3
Error:
Path must be a string.Received  {http:false}

nodejs -- v4.2.3
nexe -- v0.4.2

i just use express cli to create a simple app,am i missing something?

**Comment by lionel590** [comment]
Same problem here
nodejs > 4.2.1
bexe > 0.4.2

**Comment by Gawran** [comment]
Same problem here.
nodejs 4.1.0
nexe 0.4.2

**Comment by jaredallard** [comment]
Interesting. Must be Node 4.x.x included.

**Comment by drahgon55** [comment]
same problem. 

I tried on 0.11.x and 0.12.x versions of node also. Same error. commenting out express require line got it to compile. 

I am going to try to just drop express and use the builtin http module for the moment.

**Comment by Gawran** [comment]
You do not have to drop express. It is good thing we can trick the nexe not to bundle Express. What I did is pretty much what is written in documentation. I installed express via npm locally and then did this:

var incExpress = 'express';
var express = require(incExpress); //dynamic 
var app = express();
 /* ...rest of your code ... */

Then deploy node_modules folder along with the binary.
I think it is acceptable since I would not like my binary to be huge. I just want to kinda hide some important configurations and avoid installing node.js on every machine where I need node app to run.

By the way jaredallard - great job and thank you.

**Comment by drahgon55** [comment]
Yea I know I could still have node_modules folder but for my project I want everything to be included in the binary

**Comment by jaredallard** [comment]
Has anyone tried using the browserify branch? May help.

On Sat, Jan 09, 2016 at 12:26 PM, drahgon55 < notifications@github.com [notifications@github.com] > wrote:
Yea I know I could still have node_modules folder but for my project I want
everything to be included in the binary

—
Reply to this email directly or view it on GitHub
[https://github.com/jaredallard/nexe/issues/157#issuecomment-170278794] .[https://github.com/notifications/beacon/ACR9NW5TJg6L6vGDfDL5keI_JCmPrZsxks5pYWRjgaJpZM4G5KQg.gif]

**Comment by oleib** [comment]
Hi, same problem here. I used Node 4.2.3, nexe 0.4.2.
I need to have express bundled with the binary... Thanks.

**Comment by jaredallard** [comment]
I'll conduct a test today.

**Comment by jaredallard** [comment]
Fixed! Use `npm@1.0.0` :)

Let me know if you run into any more issues!

**Comment by oleib** [comment]
Hi @jaredallard  thank you so much!
I will check it out soon...
