### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by trenkenshu** [jaredallard/nexe#194]
Hi! First of all let me say "thank you" to all the Nexe developers and contributors.

While I was messing with Node.js compilators such as EncloseJS and JXcore, I noticed that there is allways a statement like "compiled binary runs X% slower than plain js compiled during runtime".

So, I'd like to know if anybody tried to test Nexe packages vs usual Node.js performance? 
Thanks!

**Comment by jaredallard** [comment]
So, from my viewpoints the big differences just seem to be that it handles it much like an internal library. It bundles it inside removing the need to utilize extra I/O in order to load the scripts. Also, since all `require` calls are basically pointed at the same script that eliminates even more I/O and utilizes memory instead of disk. This has a big impact on script start times, and could have an untested impact on script execution time. EncloseJS would have more of a performance gain as it also compiles it down to bytecode, nexe does not (however because we compile node.js we can also offer local machine improvements like; `-march=native`, `-O3` and other fine grained compiler opts. I could look into making usage tests down the road to give a good graph of by version improvements as well as others; i.e basic compiled vs not.

**Comment by trenkenshu** [comment]
Hello, @jaredallard!So if I get you right, Nexe does not prebuild project js and only include its files into Node library set, so it compiles each execution as a regular project? This, I think, would mean that there is no performance drop. 

EncloseJS does compile bytecode and the downside of this is it doesn't utilize CPU's specific features in order to make the bytecode compatible with any other CPU.

**Comment by jaredallard** [comment]
@trenkenshu Yup, it literally just bundles everything in separate "namespaces" and then emulates require calls so that it all works in a single file, then includes that single file as a library inside of the node.js executable.

**Comment by trenkenshu** [comment]
Ok, I get it now. Thanks!

**Comment by kanezch** [comment]
@jaredallard I still confused that whether the output of nexe is a binary file like results from a compiled cpp file by gcc, or it is just a package of nodejs source code and some xxx.js files?
I am new to node and Nexe, tks

**Comment by calebboyd** [comment]
The output of nexe is a binary file, exactly like the nodejs binary. Except nexe is built to run your script instead of the REPL. Your script (bundle) isn't treated any differently than a node built-in, like http. It exists in plain text within the binary

**Comment by kanezch** [comment]
So, if I get your point, the source code(xx.js) has never been compiled into Machine Code，they are just packed into one file, so there is no performance loss theoretically.Besides, you said that plain text is acturelly inside the binary file, I worried about that maybe it is easy to decompress/decompile the binary file because recently we are considering to use Nexe to protect our source code.

**Comment by calebboyd** [comment]
Correct, Since JavaScript is an interpreted language a function may be JIT compiled differently each time it runs depending on its execution patterns. Code security has not been a goal of this project in the past. That being said you could use something like a startup snapshot to _maybe_ secure your code. It essentially loads prepopulates the heap with parsed/tokenized js. This has been added to nexe (at least in current master). But you're right, without that - Its incredibly simple to open the binary in a text editor and extract plain JavaScript.

**Comment by quangduy90** [comment]
I'm using Nexe to project my code, is that easily to decompile ?

**Comment by calebboyd** [comment]
https://github.com/nexe/nexe/issues/194#issuecomment-295041582
