### ISSUE TITLE
How to lazy load existing modules from path | No such native module

### ISSUE THREAD

**Issue by gbaumgart** [jaredallard/nexe#273]
Hi,
I am using nexe since a while already and I am fully aware about the problem of dynamic modules.

However, there are reasons why i don't want certain modules embedded, so i hided the require like this: 

// Load dojo/dojo
var _re = require;
var _dUrl = path.resolve("./dojo/dojo.js");
_re(_dUrl);

which gives me: 
No such native module /PMaster/projects/x4mm/server/nodejs2/dist/linux_64/dojo/dojo.js
    at NativeModule.require (bootstrap_node.js:435:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at Object.__dirname.337../dojoConfig (nexe.js:47749:1)
    at s (nexe.js:1:316)
    at e (nexe.js:1:487)
    at nexe.js:1:505
    at NativeModule.compile (bootstrap_node.js:502:7)
    at Function.NativeModule.require (bootstrap_node.js:443:18)
    at Function.Module._load (module.js:426:25)

However, the file /PMaster/projects/x4mm/server/nodejs2/dist/linux_64/dojo/dojo.js really exists and i am surprised this doesn't work. 

Is there a trick to get requires working as normal? I had to modify an older nexe version for that already but it doesn't seem to work with your latest version.

thanks a lot

**Comment by rahul-dutt-sharma** [comment]
use global.require for excluded modules

On 05-Nov-2016, at 19:36, gbaumgart <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I am using nexe since a while already and I am fully aware about the problem of dynamic modules.

However, there are reasons why i don't want certain modules embedded, so i hided the require like this:

// Load dojo/dojo
var _re = require;
var _dUrl = path.resolve("./dojo/dojo.js");
_re(_dUrl);

which gives me:
No such native module /PMaster/projects/x4mm/server/nodejs2/dist/linux_64/dojo/dojo.js
at NativeModule.require (bootstrap_node.js:435:13)
at s (nexe.js:1:176)
at nexe.js:1:367
at Object.__dirname.337../dojoConfig (nexe.js:47749:1)
at s (nexe.js:1:316)
at e (nexe.js:1:487)
at nexe.js:1:505
at NativeModule.compile (bootstrap_node.js:502:7)
at Function.NativeModule.require (bootstrap_node.js:443:18)
at Function.Module._load (module.js:426:25)

However, the file /PMaster/projects/x4mm/server/nodejs2/dist/linux_64/dojo/dojo.js really exists and i am surprised this doesn't work.

Is there a trick to get requires working as normal? I had to modify an older nexe version for that already but it doesn't seem to work with your latest version.

thanks a lot

-

**Comment by gbaumgart** [comment]
that worked ! thanks a lot!

**Comment by rahul-dutt-sharma** [comment]
this is one thing that def needs to make it to the projects readme. I almost quit because I could not figure it out. on the retrospect I am glad it was not there cause it made me read the code and understand what was going on under the hood ?

On 05-Nov-2016, at 20:12, gbaumgart <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #273<https://github.com/jaredallard/nexe/issues/273>.

-

**Comment by bchr02** [comment]
I am trying to use the global.require technique but that does not work using latest LTS version of node. I keep getting:
`TypeError: global.require is not a function` 
Does anyone have any ideas? Thank you.

**Comment by jaredallard** [comment]
I'll look into this sorry for the delay on this project. I've a lot of backlog in life that doesn't seem to ever end.
